apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: harmonycore-test
  name: harmonycore-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: harmonycore-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harmonycore-test
    spec:
      containers:
      - name: test-harmonycore
        image: jeffkube.azurecr.io/testk3s/harmonycore
        env:
        - name: LM_HOST
          value: comet.synergex.loc
        ports:
        - containerPort: 8086
  