#!/bin/bash

if [ -x setup ]
then
    source setup
fi

if [ -z "$LM_HOST" ]
then
    echo -e "\nMissing config info. Set LM_HOST\n"
else
    docker build \
	    -f synergy1211.Dockerfile \
	    --build-arg LM_HOST=$LM_HOST \
	    -t synergy1211 .
fi
